"""Acceptance contract for the (flow-generated) SVG renderer ``flow.graph.to_svg``.

This is the SPEC the code generator must satisfy. ``to_svg(wf) -> str`` renders a
workflow to a standalone, valid SVG document using Graphviz (via pydot + the
system ``dot`` binary) for auto-layout when available, and a deterministic
hand-assembled fallback (``_to_svg_fallback``) when ``dot`` is not present.

The contract is renderer-agnostic on shape details (Graphviz draws rounded boxes
as ``<polygon>``, the fallback uses ``<rect>``) — it pins the invariants that
matter: valid SVG, every node id present, conditional/loop edges labelled,
determinism, empty-workflow safety, and that the fallback still produces a valid,
embeddable SVG.
"""

from __future__ import annotations

import shutil
import xml.etree.ElementTree as ET

from flow.graph import _to_svg_fallback, to_svg
from flow.models import Condition, EdgeDef, NodeDef, WorkflowDef

_SVG_NS = "http://www.w3.org/2000/svg"
_HAS_DOT = shutil.which("dot") is not None


def _wf() -> WorkflowDef:
    return WorkflowDef(
        name="demo",
        provider="copilot",
        entry="a",
        default_model="m",
        nodes=(
            NodeDef(id="a", type="agent", prompt="p", output="x"),
            NodeDef(id="b", type="script", run="flow.tools:passthrough", output="y"),
            NodeDef(id="c", type="agent", prompt="q", output="z"),
        ),
        edges=(
            EdgeDef(src="a", dst="b"),
            EdgeDef(src="b", dst="c"),
            EdgeDef(
                src="c",
                dst="b",
                when=Condition(op="contains", value="{{z}}", text="REVISE"),
                loop_max=2,
            ),
        ),
    )


def _svg_root(svg: str) -> ET.Element:
    return ET.fromstring(svg)


# --- invariants that hold for BOTH renderers ---------------------------------


def test_to_svg_is_valid_xml_with_svg_root() -> None:
    root = _svg_root(to_svg(_wf()))
    assert root.tag in ("svg", f"{{{_SVG_NS}}}svg")


def test_to_svg_contains_every_node_id() -> None:
    svg = to_svg(_wf())
    for node_id in ("a", "b", "c"):
        assert node_id in svg


def test_to_svg_has_a_shape_per_node() -> None:
    """Each node yields at least one drawn shape (rect for fallback, polygon for
    Graphviz)."""
    root = _svg_root(to_svg(_wf()))
    shapes = [el for el in root.iter() if el.tag.rsplit("}", 1)[-1] in ("rect", "polygon", "ellipse")]
    assert len(shapes) >= 3


def test_to_svg_labels_conditional_edge() -> None:
    svg = to_svg(_wf())
    assert "REVISE" in svg or "contains" in svg


def test_to_svg_is_deterministic() -> None:
    wf = _wf()
    assert to_svg(wf) == to_svg(wf)


def test_to_svg_empty_workflow_is_valid() -> None:
    wf = WorkflowDef(name="empty", provider="copilot", entry="", nodes=(), edges=())
    root = _svg_root(to_svg(wf))
    assert root.tag in ("svg", f"{{{_SVG_NS}}}svg")


# --- Graphviz path (only when dot is installed) ------------------------------


def test_to_svg_uses_graphviz_when_available() -> None:
    if not _HAS_DOT:
        return  # environment without Graphviz — covered by the fallback tests
    svg = to_svg(_wf())
    # Graphviz fingerprint: it emits a "Generated by graphviz" comment and pt units.
    assert "graphviz" in svg.lower() or "pt" in svg[:400]


# --- fallback path (dependency-free, always available) -----------------------


def test_fallback_is_valid_and_has_rects() -> None:
    svg = _to_svg_fallback(_wf())
    root = _svg_root(svg)
    assert root.tag in ("svg", f"{{{_SVG_NS}}}svg")
    rects = [el for el in root.iter() if el.tag.rsplit("}", 1)[-1] == "rect"]
    assert len(rects) >= 3


def test_fallback_is_deterministic_and_labels_edges() -> None:
    wf = _wf()
    svg = _to_svg_fallback(wf)
    assert _to_svg_fallback(wf) == svg
    assert "REVISE" in svg or "contains" in svg
    for node_id in ("a", "b", "c"):
        assert node_id in svg


def test_fallback_empty_workflow_is_valid() -> None:
    wf = WorkflowDef(name="empty", provider="copilot", entry="", nodes=(), edges=())
    root = _svg_root(_to_svg_fallback(wf))
    assert root.tag in ("svg", f"{{{_SVG_NS}}}svg")
